/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ora.biblioapp.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import ora.biblioapp.controller.LibrosController;
import ora.biblioapp.controller.PedidoController;
import ora.biblioapp.domain.LibrosBean;
import ora.biblioapp.util.AppUtil;
import ora.biblioapp.util.Memoria;
import ora.biblioapp.util.Mensajes;



/**
 *
 * @author Claudia
 */
public class AutoresView extends javax.swing.JInternalFrame {
 private List<LibrosBean> lista;
  private LibrosController control;
    /**
     * Creates new form AutoresView
     */
    public AutoresView() {
        initComponents();
            control = new LibrosController();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        txtisbn = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtobra = new javax.swing.JTextField();
        txtciudad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblautor = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("AUTORES ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Codigo_libro:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 210, 30));

        jLabel3.setText("Apellidos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setText("Ciudad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 210, 30));
        getContentPane().add(txtisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 130, 30));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 210, 30));

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setText("Obra:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setText("ISBN:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        getContentPane().add(txtobra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 130, 30));
        getContentPane().add(txtciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, 30));

        tblautor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "APELLIDOS", "NOMBRE", "CIUDAD", "OBRA", "ISBN"
            }
        ));
        jScrollPane1.setViewportView(tblautor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 600, 260));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/19185453291389592180.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 40, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 40, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/noticias_registro_icono.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Consulta.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 40, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nbhbb.gif"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 320, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
 try {
      // Datos
      LibrosBean bean = new LibrosBean();
      bean.setCodigo(txtcodigo.getText());
      bean.setApellidos(txtapellidos.getText());
      bean.setNombre(txtnombre.getText());
      bean.setCiudad(txtciudad.getText());
     bean.setObra(txtobra.getText());
      bean.setIsbn(txtisbn.getText());
   
       
      // Proceso
      lista = control.traerLibros(bean);
      // Reporte
      mostrarClientes();
    } catch (Exception e) {
      Mensajes.showError(rootPane, e.getMessage());
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    LibrosBean bean = new LibrosBean();
    bean.setCodigo("NONE");
    EditarLibros view = new EditarLibros(null, true);
    view.setAccion(AppUtil.CRUD_NUEVO);
    Memoria.put("bean", null);
    view.setVisible(true);
    if(Memoria.get("bean") == null){
      return;
    }
    bean = (LibrosBean) Memoria.get("bean");
    lista.add(0, bean);
    mostrarClientes();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblautor;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtciudad;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtisbn;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtobra;
    // End of variables declaration//GEN-END:variables
 private void mostrarClientes() {
    DefaultTableModel tabla;
    tabla = (DefaultTableModel) tblautor.getModel();
    tabla.setRowCount(0);
    if (lista == null || lista.isEmpty()) {
      return;
    }
    for (LibrosBean bean : lista) {
      Object[] rowData = {bean.getCodigo(),
        bean.getApellidos(), bean.getNombre(),
        bean.getCiudad(),bean.getObra(), bean.getIsbn()};
      tabla.addRow(rowData);
    }
  }

}

