/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ora.biblioapp.view;

import ora.biblioapp.controller.LibrosController;
import ora.biblioapp.domain.LibrosBean;
import ora.biblioapp.util.AppUtil;
import ora.biblioapp.util.Memoria;
import ora.biblioapp.util.Mensajes;


/**
 *
 * @author GustavoCoronel
 */
public class EditarLibros extends javax.swing.JDialog {
  
  private String accion;
  private LibrosBean bean;

  /**
   * Creates new form EditarCliente
   */
  public EditarLibros(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtciudad = new javax.swing.JTextField();
        txtobra = new javax.swing.JTextField();
        txtisbn = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDITAR");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 91, -1));

        jLabel2.setText("Apellidos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 91, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, 91, -1));

        jLabel4.setText("Ciudad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, 91, -1));

        jLabel5.setText("Obra:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, 91, -1));

        jLabel6.setText("ISBN:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 91, -1));

        txtcodigo.setEditable(false);
        txtcodigo.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 17, 191, -1));
        getContentPane().add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 51, 191, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 85, 191, -1));
        getContentPane().add(txtciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 119, 191, -1));
        getContentPane().add(txtobra, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 153, 191, -1));
        getContentPane().add(txtisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 187, 191, -1));

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 131, 52));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 131, 52));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    this.dispose();
  }//GEN-LAST:event_btnCancelarActionPerformed

  private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
    try {
      // Datos
      LibrosBean bean = new LibrosBean();
      bean.setCodigo(txtcodigo.getText());
      bean.setApellidos(txtapellido.getText());
      bean.setNombre(txtnombre.getText());
      bean.setCiudad(txtciudad.getText());
     bean.setObra(txtobra.getText());
      bean.setIsbn(txtisbn.getText());
   
      // Proceso
      LibrosController control = new LibrosController();
      control.procesar(accion, bean);
      // Reporte
      Memoria.put("bean", bean);
      this.dispose();
    } catch (Exception e) {
      Mensajes.showError(rootPane, e.getMessage());
    }
  }//GEN-LAST:event_btnGrabarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(EditarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(EditarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(EditarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(EditarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>
        //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        EditarLibros dialog = new EditarLibros(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtciudad;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtisbn;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtobra;
    // End of variables declaration//GEN-END:variables

  void setAccion(String accion) {
    this.accion = accion;
    String titulo = accion + "LIBROS";
    this.setTitle(titulo);
    habilitarControles();
  }

  void setBean(LibrosBean bean) {
    this.bean = bean;
    cargarDatos();
  }

  private void cargarDatos() {
    txtcodigo.setText(bean.getCodigo());
    txtapellido.setText(bean.getApellidos());
    txtnombre.setText(bean.getNombre());
    txtciudad.setText(bean.getCiudad());
    txtobra.setText(bean.getObra());
    txtisbn.setText(bean.getCiudad());
  
  }

  private void habilitarControles() {
    boolean editable = true;
    if(accion.equals(AppUtil.CRUD_ELIMINAR)){
      editable = false;
    }
    txtapellido.setEditable(editable);
    txtnombre.setEditable(editable);
    txtciudad.setEditable(editable);
    txtobra.setEditable(editable);
    txtisbn.setEditable(editable);
   
  }
}
